<a href="https://colab.research.google.com/github/SadeemAlasiri/Ex_week3/blob/main/Copy_of_SVD_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**SVD**

#import libraries

In [1]:
import numpy as np

#Load the tabular dataset :

dataset :


    [1, 2, 1, 0, 4],

    [2, 3, 4, 0, 2],

    [3, 1, 1, 0, 5],

    [4, 0, 2, 5, 0],

    [5, 4, 0, 1, 2]


In [10]:
data_ar=([[1, 2, 1, 0, 4],

     [2, 3, 4, 0, 2],

     [3, 1, 1, 0, 5],

     [4, 0, 2, 5, 0],

     [5, 4, 0, 1, 2]])

In [11]:
data_ar

[[1, 2, 1, 0, 4],
 [2, 3, 4, 0, 2],
 [3, 1, 1, 0, 5],
 [4, 0, 2, 5, 0],
 [5, 4, 0, 1, 2]]

#Perform Singular Value Decomposition (SVD)


In [13]:
U, s, VT = np.linalg.svd(data_ar)

# Extract the singular values and vectors

In [14]:
singular_values = np.diag(s)
left_singular_vectors = U
right_singular_vectors = VT.T

# Perform dimensionality reduction by selecting top k singular values and vectors


In [15]:
k = 2
reduced_dataset = np.dot(np.dot(left_singular_vectors[:, :k], singular_values[:k, :k]), right_singular_vectors[:, :k].T)

# Print the original and reduced datasets


In [18]:
print("Original data_ar:")
print(data_ar)
print(reduced_dataset)

Original data_ar:
[[1, 2, 1, 0, 4], [2, 3, 4, 0, 2], [3, 1, 1, 0, 5], [4, 0, 2, 5, 0], [5, 4, 0, 1, 2]]
[[ 1.68517423  2.16823828  1.03211446 -0.78448115  3.35352314]
 [ 2.74997839  2.2474459   1.40223771  0.45592685  3.01586488]
 [ 2.65238506  2.68115204  1.46466169 -0.25083665  3.88603508]
 [ 4.38005462  0.72090701  1.60881922  4.57102627 -0.63704194]
 [ 4.0133692   2.54718625  1.88634605  1.65093492  3.00682541]]


#**Well done :)**